[package]
name = "physics-graph"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
rusttype = "0.9.3"
serde_json = "1.0.90"
